/*
 * THIS DEFINATION IS FOR INPUT PIN
 */

int RC_1_PWM, RC_2_PWM, RC_3_PWM, RC_4_PWM, RC_5_PWM ;

int FILTER_NUM = 5;

int RC_1_SUM_FILTER[10];
int RC_2_SUM_FILTER[10];
int RC_3_SUM_FILTER[10];
int RC_4_SUM_FILTER[10];
int RC_5_SUM_FILTER[10];

int RC_1_SUM,RC_2_SUM,RC_3_SUM,RC_4_SUM,RC_5_SUM
